apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ./docker-compose.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mqtt
  name: mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mqtt
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ./docker-compose.yml convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: mqtt
    spec:
      containers:
        - image: eclipse-mosquitto
          name: mqtt
          ports:
            - containerPort: 1883
          resources: {}
          volumeMounts:
            - mountPath: /mosquitto/config
              name: mqtt-claim0
            - mountPath: /mosquitto/data
              name: mqtt-claim1
      restartPolicy: Always
      volumes:
        - name: mqtt-claim0
          persistentVolumeClaim:
            claimName: mqtt-claim0
        - name: mqtt-claim1
          persistentVolumeClaim:
            claimName: mqtt-claim1
status: {}
