apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ./docker-compose.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: node-red
  name: node-red
spec:
  ports:
    - name: "1880"
      port: 1880
      targetPort: 1880
  selector:
    io.kompose.service: node-red
status:
  loadBalancer: {}
